version: '3'
services:
  db:
    image: mysql:5.7
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: .env
    volumes:
      - /opt/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
  app:
    build: .
    container_name: app
    env_file: .env
    volumes:
      - .:/home/app/rails-app
    depends_on:
      - db
      - redis
  web:
    image: nginx-certbot
    container_name: web
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    # volumes:
    #   - /opt/log/nginx:/var/log/nginx
    #   - /opt/nginx/conf.d:/etc/nginx/conf.d
    #   - /opt/letsencrypt:/etc/letsencrypt
    restart: always
    depends_on: 
      - app
    env_file: .env
