version: '3'
services:
  db:
    image: mysql:5.7
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: .env
    volumes:
      - /tmp/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
  web:
    build: .
    container_name: web
    env_file: .env
    volumes:
      - .:/home/app/rails-app
    ports:
      - "80:80"
    depends_on:
      - db
      - redis
