files:
  common.yml: "https://docs.google.com/spreadsheets/d/166f7AbpvXSYRTgw_tpFbrbe6sTcZi6wJ5x9qtxYouhk/pub?gid=431875857&single=true&output=csv"
  devise.yml: "https://docs.google.com/spreadsheets/d/1I7YYl5B_sCL6dogYbOya1VKY5LBmQ7yfoyfwu_BgArE/pub?gid=1167142122&single=true&output=csv"
  doorkeeper.yml: "https://docs.google.com/spreadsheets/d/1cJMWtOi0WgRwm2fgfISfPhFtvz5TMoN-b4vHe-i_LH4/pub?gid=1479695187&single=true&output=csv"
  help.yml: "https://docs.google.com/spreadsheets/d/1ABigBiQ67o0m_5eh63TkX7aNJz6w8HEU17KDEH4TnsQ/pub?gid=672224866&single=true&output=csv"
  mailer.yml: "https://docs.google.com/spreadsheets/d/1XshaTLD2Imse2ZlCRC-mH0lufialc1ZVnTI0qVjdTjE/pub?gid=202408012&single=true&output=csv"
  upnp_description.yml: "https://docs.google.com/spreadsheets/d/1MRssT_ZjnwByl3lc5tEXbiRzcJfAlmxSskqZimRBxvA/pub?gid=869358020&single=true&output=csv"
  user.yml: "https://docs.google.com/spreadsheets/d/11mIAtB22Uo7IsKtoujsVYi_Z30fWvWXEme24-ADmk_M/pub?gid=1973858568&single=true&output=csv"
